### PR TITLE
HocVienTruyenTranh - Fix Referer

### LINKED ISSUE #2482: [Bug] Hocvientruyentranh extension is still not loading Image
### Device information
* Tachiyomi extension version: 1.2.7
* Tachiyomi version: 0.8.5
* Android version: 8

After updated , Extension is still not loading some chapters , 
Example : https://hocvientruyentranh.net/chapter/203344/nanatsu-no-taizai-chapter-344-raw or https://hocvientruyentranh.net/chapter/204769/act-age-chapter-104
 those chapters still load on normal Browser or Webview , but it's got error in tachiyomi  
image

### PR DESCRIPTION
**Pull request by happywillow0**
- Change imgheader to global Refer (fixes #2482)
- Made IDE recommended code changes
- Reformat code
- Optimize Imports

### CODE REVIEW

File: src/vi/academyvn/src/eu/kanade/tachiyomi/extension/vi/academyvn/HocVienTruyenTranh.kt [hunk 1]
```diff
@@ -138,65 +153,58 @@ class HocVienTruyenTranh : ParsedHttpSource() {
         return pages
     }
 
-    override fun imageRequest(page: Page): Request {
-        val imgHeaders = headersBuilder().add("Referer", page.url).build()
```
Comment (happywillow0) [inline src/vi/academyvn/src/eu/kanade/tachiyomi/extension/vi/academyvn/HocVienTruyenTranh.kt]: I didn't notice it on the previous pull request but page.url actually is blank so the referrer actually do anything.
