### PR TITLE
[Ready] TMO Update

### LINKED ISSUE #1749: TuMangaOnline
Device information
Tachiyomi error extensión TuMangaOnline
## Steps to reproduce
1. Entras a un manga y sale un mensaje 
2. 
Screenshot_20191105-142519_Tachiyomi

### PR DESCRIPTION
**Pull request by happywillow0**
This PR should be ready to pull pending any further changes from TMO. It has been a few days since their last (daily) change. We can still wait some more to see if anything changes... again. 

This should fix #1749

Current revisions:

- Revert pageListParse
- Chapter URL are no longer directly linked from manga page. Read button is an actual button with a scripted click action. This now pulls the chapter ID and requests viewer url via POST.

FAQ Reminder that needs to be posted: 
Since chapter URLs have been updated, the chapter lists in the library need to be pulled to refresh.

### CODE REVIEW

File: src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt [hunk 1]
```diff
@@ -246,30 +247,34 @@ class TuMangaOnline : ConfigurableSource, ParsedHttpSource() {
     private fun parseChapterDate(date: String): Long = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).parse(date).time
 
     override fun pageListRequest(chapter: SChapter): Request {
-        val url = getBuilder(baseUrl + chapter.url).substringBeforeLast("/") + "/cascade"
+        val chapterid = chapter.url.substringBefore("&")
+        val token = chapter.url.substringAfter("&")
+        val goto = "$baseUrl/goto/$chapterid/f454f714874fa4edbb7076d727887062"
```
Comment (happywillow0) [inline src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt]: URL is  `var url_goto = 'https://tmofans.com/goto/:GO_TO_ID/:HASH';` 

The current hash is f454f714874fa4edbb7076d727887062 but I'm not sure where it is from. It stays the same between my phone, firefox and chrome but it may change based on how the server is generating this. This may be able to be pulled from the javascript code.

**Comment by happywillow0** [comment]
Tested and working for me. 

I realized the data was unicode encoded because I was working with the unicode emojis but I didn't actually decode them until today. 

<details>
 <summary>I decided to manually de-obfuscate for anyone who is curious</summary>

        function _5dcdfa6b6458c(_0x5908x2){
		var _0x5908x3=document[createElement](form);
		_0x5908x3[setAttribute](method,post);
		_0x5908x3[setAttribute](action,url_goto[replace](:GO_TO_ID,_0x5908x2)[replace](:HASH,f454f714874fa4edbb7076d727887062));
		var _0x5908x4=document[createElement](input);
		_0x5908x4[setAttribute](type,hidden);
		_0x5908x4[setAttribute](name,_token);
		_0x5908x4[setAttribute](value,*your token here*);
		_0x5908x3[appendChild](_0x5908x4);
		document[body][appendChild](_0x5908x3);
		_0x5908x3[submit]()}

</details>

**Comment by happywillow0** [comment]
And they changed it again 😢 We can keep an eye on it and see if they keep the new method or not.

**Comment by edgarMejia** [comment]
It's working?

**Comment by happywillow0** [comment]
Yes, for now. You can build off of my code or I can send you the unsigned apk if that is allowed. 

However, it is the holidays. The last time, the site stayed the same for 10 days or so before it changed again so I'm not sure how long we should wait and check for before this gets merged.

**Comment by edgarMejia** [comment]
I was reviewing today the corrections you have made and still working, I will continue to check if they make any changes.

**Comment by edgarMejia** [comment]
It's still working.
