### PR TITLE
Fix Golden Manga due to site redesign

### LINKED ISSUE #4297: Golden Mangás extension not working
The following error appears when trying to read a manga from that source:
Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object reference

### PR DESCRIPTION
**Pull request by alessandrojean**
Closes #4297.

### CODE REVIEW

File: src/pt/goldenmangas/src/eu/kanade/tachiyomi/extension/pt/goldenmangas/GoldenMangas.kt [hunk 1]
```diff
@@ -45,12 +47,15 @@ class GoldenMangas : ParsedHttpSource() {
...
 
     override fun popularMangaFromElement(element: Element): SManga = SManga.create().apply {
-        title = element.select("h3").first().text().withoutLanguage()
-        thumbnail_url = element.select("img").first()?.attr("abs:src")
-        url = element.attr("href")
+        title = element.select("img").attr("alt")
+            .substringAfter("online ")
+            .withoutLanguage()
+        thumbnail_url = element.select("img").attr("abs:data-src")
+        url = "/" + element.attr("href")
```
Comment (SnakeDoc83) [inline src/pt/goldenmangas/src/eu/kanade/tachiyomi/extension/pt/goldenmangas/GoldenMangas.kt:58]: This is fine, but I'll mention that a good alternative to this is `setUrlWithoutDomain("abs:href")` (using `abs` will get you the preceding `/`.
