### PR TITLE
Fix MRM Filter IOException

### LINKED ISSUE #1557: MyReadingManga forces to uninstall
Happened yesternight. I thought I accidentally uninstall it so I reinstalled it. But it happened again- thrice the whole night and twice this morning.

Edit: okay, it disappears but would be back after a while then disappear again.

Tachiyomi ver. 1.8.4
MyReadingManga ver. 1.2.26

### PR DESCRIPTION
**Pull request by happywillow0**
Fixes #1557 

[Unhanded exception](https://kotlinlang.org/docs/reference/exceptions.html) [IOException from OKHTTPClient](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-call/execute/) is now taken care of. 
Added some [null safety](https://kotlinlang.org/docs/reference/null-safety.html) for filters due to IOException

Tested online
Tested offline, did not crash on my phone.

### CODE REVIEW

File: src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt [hunk 1]
```diff
@@ -213,10 +214,10 @@ open class MyReadingManga(override val lang: String) : ParsedHttpSource() {
     override fun imageUrlParse(document: Document) = throw Exception("Not used")
 
     //Filter Parsing, grabs home page as document and filters out Genres, Popular Tags, and Catagorys
-    private val filterdoc = OkHttpClient().newCall(GET("$baseUrl", headers)).execute().asJsoup()
-    private val genresarray = filterdoc.select(".tagcloud a[href*=/genre/]").map { Pair(it.attr("href").substringBeforeLast("/").substringAfterLast("/"), it.text())}.toTypedArray()
-    private val poptagarray = filterdoc.select(".tagcloud a[href*=/tag/]").map { Pair(it.attr("href").substringBeforeLast("/").substringAfterLast("/"), it.text())}.toTypedArray()
-    private val cattagarray = filterdoc.select(".level-0").map { Pair(it.attr("value"), it.text())}.toTypedArray()
+    private val filterdoc:Document? = try { OkHttpClient().newCall(GET("$baseUrl", headers)).execute().asJsoup() } catch (e: IOException) {null}
```
Comment (happywillow0) [inline src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt]: I would like to use `client.newCall(GET("$baseUrl", headers)).execute()` instead of  `OkHttpClient()` but Android Studio warns "Accessing non-final property client in constructor"

Is this of any importance? 
It works as currently coded.

Comment (joseph619) [reply src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt]: You should as for a PR review I guess
