### PR TITLE
Fix #5095 and #5082

### LINKED ISSUE #5095: [Bug] <Jinmantiantang>: <Manga description is missing>
Device information
- Tachiyomi version: SY Stable 1.3.1
- Android version: 8

Source information
- Name: Jinmantiantang (禁漫天堂）
- Extension version: 1.2.7

Steps to reproduce
1. Check any mangas with description

Expected behavior
Manga description should appear 

Actual behavior
The manga description is missing

### PR DESCRIPTION
**Pull request by antonycaporossi**
Fixes and closes #5095 and #5082

### CODE REVIEW

File: src/en/manhwamanga/src/eu/kanade/tachiyomi/extension/en/manhwamanga/ManhwaManga.kt [hunk 1]
```diff
@@ -1,93 +1,98 @@
...
+import eu.kanade.tachiyomi.util.asJsoup
 import okhttp3.HttpUrl
-import okhttp3.OkHttpClient
 import okhttp3.Request
+import okhttp3.RequestBody
+import okhttp3.Response
 import org.jsoup.nodes.Document
 import org.jsoup.nodes.Element
 
-@Nsfw
```
Comment (arkon) [inline src/en/manhwamanga/src/eu/kanade/tachiyomi/extension/en/manhwamanga/ManhwaManga.kt:16]: Do not remove this.

**Comment by antonycaporossi** [comment]
Sorry my bad. Now should be fine
