### PR TITLE
Madara Updates

### LINKED ISSUE #2325: [Bug] EarlyManga : Images being replaced
### Device information
* Tachiyomi extension version: Madara 1.2.57
* Tachiyomi version: 0.8.4
* Android version: 9

## Steps to reproduce
1. Try to read any chapter from any manga from EarlyManga source

### Expected behavior
The pages of the chapter appear for reading.

### Actual behavior
The image will appear blurred with text over it like the following image.
Screenshot_20200301-063533

### PR DESCRIPTION
**Pull request by happywillow0**
- Add MangaBob #2312
- Fixes #2325 EarlyManga 
- Update APC UserAgent

### CODE REVIEW

File: src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt [hunk 1]
```diff
@@ -221,7 +222,7 @@ class GetManhwa : Madara("GetManhwa", "https://getmanhwa.co", "en")
 
 class AllPornComic : Madara("AllPornComic", "https://allporncomic.com", "en") {
     override val client: OkHttpClient = network.client
-    private val userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36"
+    private val userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"
```
Comment (arkon) [inline src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt]: I feel like they're using more than just the user agent since they can't possibly expect every user to have the latest stable Chrome version. It's fine if this works for us though.
