### PR TITLE
Fix Plot Twist no Fansub, Update LectorManga, TMOHentai and TMO

### LINKED ISSUE #4108: [Bug] Kumanga: Error 400
## Device information
- Tachiyomi version: Stable 0.10.4
- Android version: 10

## Source information
- Name: Kumanga
- Extension version: 1.2.5

## Steps to reproduce
1. Browse all mangas

### Expected behavior
Get list of all mangas

### Actual behavior
Error 400

## Other details
N/A

### LINKED ISSUE #4109: [Bug] Plot Twist no Fansub: Latest url return 404
## Device information
- Tachiyomi version: Stable 0.10.4
- Android version: 10

## Source information
- Name: Plot Twist No Fansub
- Extension version: 1.2.1

## Steps to reproduce
1. Browse latest

### Expected behavior
Get list of latest mangas

### Actual behavior
Error 404

## Other details
N/A

### PR DESCRIPTION
**Pull request by edgarMejia**
## Plot Twist no Fansub
- [x] Closes #4109 

## TMO Sources
- [x] LectorManga: Add support to opening links from the website in main app
- [x] TMO: Add support to opening links from the website in main app
- [x] TMOHentai: Add support to opening links from the website in main app

### CODE REVIEW

File: src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt [hunk 1]
```diff
@@ -61,13 +61,15 @@ class Kumanga : HttpSource() {
...
+
+    // They add various fake tokens but the chosen one always starts with "eyJjdCI6I"
+    private val tokenRegex = Regex(""""(eyJjdCI6I[^"\s]{100,})"""")
 
     private fun getKumangaToken() {
         kumangaToken = client.newCall(GET("$baseUrl/mangalist?&page=1", headers)).execute().asJsoup()
             .select("div.input-group [type=hidden]")
             .firstOrNull()
-            ?.let { tokenRegex.find(it.outerHtml())?.groupValues?.get(1) }
+            ?.let { tokenRegex.find(it.outerHtml())!!.value }
```
Comment (SnakeDoc83) [inline src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt:72]: `?` instead of `!!`

Comment (SnakeDoc83) [reply src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt:72]: And did you test this? I haven't run it, I'm a little worried about changing to `.value`

Comment (edgarMejia) [reply src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt:72]: Yes I test it with `?.groupValues?.get(1)` and `!!.value` and works with both, but I change it to `!!.value` because I think `?.groupValues?.get(1)` is used when regex returns multiple results and `!!.value` for one like this case.

Comment (jobobby04) [reply src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt:72]: Value is used to return the whole match, while group values are used to get the matches in the brackets(there can be multiple), it seems the whole regex is in brackets, which is why it could do that before

Comment (SnakeDoc83) [reply src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt:72]: `.groupValues?.get(1)` is being used to return what the regex captures in the first capture group (a capture group being what's inside `()`), `.value` returns the whole match. With this regex there should be a difference in results, one would return `token_characters` the other returning `"token_characters"` (those quotation marks could be a problem).

Comment (edgarMejia) [reply src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt:72]: Sorry, this is my first time using regex with Kotlin, so in this case the best option is `.groupValues?.get(1)`?

Comment (SnakeDoc83) [reply src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt:72]: In this case, yes, and it should be called with `?`, not `!!` because if `find` returns null we'll get an NPE and that could crash the app here.

Comment (edgarMejia) [reply src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt:72]: Thanks for the help to both

Comment (edgarMejia) [reply src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt:72]: While I made the correction, Kumanga uploaded another update, so my change is no longer functional.

Comment (AbdullahM0hamed) [reply src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt:72]: Plot Twist no Fansub, more like Plot Twist: the changes are no longer functional

Comment (edgarMejia) [reply src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt:72]: hahaha

**Comment by edgarMejia** [comment]
Hi,
is there a way to remove the Kumanga changes from this pull request?

I can't find a solution to the encryption of the images in the pUrl variable.

**Comment by AbdullahM0hamed** [comment]
Yeah, remove the changes locally, commit the removal of said changes, and then push the commit.

**Comment by edgarMejia** [comment]
> Yeah, remove the changes locally, commit the removal of said changes, and then push the commit.

Ty 🙏🏼

**Comment by edgarMejia** [comment]
Ready to merge.

**Comment by SnakeDoc83** [comment]
Think you missed updating a gradle.

**Comment by edgarMejia** [comment]
> Think you missed updating a gradle.

Thanks 😓
